---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
      orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(p8105.datasets)

nypd_complaint = 
  read_csv("./shiny/nypd_complaint_two_year_data.csv")

complaint_select=nypd_complaint %>% 
  janitor::clean_names() %>% 
  select(month,day,year,ofns_desc,susp_sex,susp_race,susp_age_group,latitude,longitude,vic_race,vic_sex,vic_age_group) %>% 
  drop_na(susp_sex,susp_race,susp_age_group,vic_race,vic_sex,vic_age_group)%>% 
  mutate(
    date=str_c(year,month,day, sep = "-"),
    location=str_c(longitude,latitude,sep=", "))

crime_type=complaint_select %>% 
  group_by(ofns_desc,year) %>% 
  summarise(obs=n()) %>% 
  filter(obs>5000)

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r, eval = FALSE}
boros = nyc_airbnb %>% 
  distinct(boro) %>%
  pull()
# selectInput widget
selectInput(
  "boro_choice", 
  label = h3("Select boro"),
  choices = boros,selected="Manhattan"
  )

max_price = 1000
min_price = nyc_airbnb %>% distinct(price) %>% min()
  
# sliderInput widget
sliderInput(
  "price_range", 
  label = h3("Choose price range"), 
  min = min_price, max = max_price, value = c(100, 400))

room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()
# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, eval = FALSE}
renderPlotly({
  nyc_airbnb %>%
  filter(
    boro == input[["boro_choice"]], 
    price %in% input[["price_range"]][1]:input[["price_range"]][2],
    room_type == input[["room_choice"]]) %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>% 
    filter(
      boros==input[["Manhattan"]],
      room_type==input[["room_choice"]])%>% 
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})
```

### Chart C

```{r}
renderPrint({ 
  input[["room_ch"]]
})
```

